/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	//INITIALIZING REGISTERS ADDRESS FOR THE BLINKING A LED OF PORT A
	uint32_t volatile *pClkCtrlReg = (uint32_t *)0x40023830;  //enabling the clock
	uint32_t volatile *pPortAModeReg = (uint32_t *)0x40020000; // PortA mode register
	uint32_t volatile *pPortAOutReg = (uint32_t *)0x40020014; //Port A pin 5 as output mode
	uint32_t volatile *pPortAInReg = (uint32_t *)0x40020010; // 0x40020000 + 0x10 (OFFSET).


	//THIS IS TO ENABLE THE CLOCK FOR THE GPIO PORT A IN THE AHB1ENR (SET THE 0th BIT position)
	*pClkCtrlReg = *pClkCtrlReg | (1 << 0);  // *pClkCtrlReg |= 0x01; //this is for Port A enable 0x01; for portB: 0x02; for portC : 0x04;

	//CONFIGURE THE MODE OF THE IO PIN AS OUTPUT
	// (CLEAR) THE 11TH AND 10TH BIT POSITIONS.
	*pPortAModeReg &= ~(3 << 10); //0xFFFFF3FF;
	//MAKE 11TH AND 10TH BIT POSTION TO 0 1 RESPECTIVLY AS OUTPUT MODE(SET)
	*pPortAModeReg |= (1 << 10);  // pin number 5 10th and 11th bit to SET.


	//Configure PA0 for input (GPIOA MODE REGISTER)
	*pPortAModeReg &= ~(3 << 0); //to take it as input.
	*pPortAOutReg &= ~(1 << 5); // TURN OFF LED BY DEFAULT.

	while(1)
	{
		//read the status of the PA0 pin (GPIO INPUT DATA REGISTER)
		uint8_t pinStatus = (uint8_t)(*pPortAInReg & 0x1); //zero out all other bits except bit 0.

		if(pinStatus){
			//turn ON LED
			*pPortAOutReg |= (1 << 5); //USING SHIFT OPERATORS. (To turn ON 5th bit on ODR.) TURN ON LED
		}
		else
			*pPortAOutReg &= ~(1 << 5); //turn OFF LED.

	//SET 5TH BIT OF THE OUTPUT DATA REGISTER(ODR) TO MAKE I/O PIN -5 AS HIGH



	}
/*	while(1){
		*pPortAOutReg |= (1 << 5);
		for (uint32_t i =0 ; i<300000 ; i++);  //random delay
		*pPortAOutReg &= ~(1 << 5); // TO Turn OFF LED.
		for (uint32_t i =0 ; i<300000 ; i++);  //random delay

	}
*/
	//while(1);
}
