/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

int main(void)
{
	//INITIALIZING REGISTERS ADDRESS FOR THE BLINKING A LED OF PORT A
	uint32_t *pClkCtrlReg = (uint32_t *)0x40023830;  //enabling the clock
	uint32_t *pPortAModeReg = (uint32_t *)0x40020000; // PortA mode register
	uint32_t *pPortAOutReg = (uint32_t *)0x40020014; //Port A pin 5 as output mode

	//THIS IS TO ENABLE THE CLOCK FOR THE GPIO PORT A IN THE AHB1ENR (SET THE 0th BIT position)
	*pClkCtrlReg = *pClkCtrlReg | (1 << 0);  // *pClkCtrlReg |= 0x01; //this is for Port A enable 0x01; for portB: 0x02; for portC : 0x04;

	//CONFIGURE THE MODE OF THE IO PIN AS OUTPUT
	// (CLEAR) THE 11TH AND 10TH BIT POSITIONS.
	*pPortAModeReg &= ~(3 << 10); //0xFFFFF3FF;
	//MAKE 11TH AND 10TH BIT POSTION TO 0 1 RESPECTIVLY AS OUTPUT MODE(SET)
	*pPortAModeReg |= (1 << 10);  // pin number 5 10th and 11th bit to SET.

	//SET 5TH BIT OF THE OUTPUT DATA REGISTER(ODR) TO MAKE I/O PIN -5 AS HIGH

	*pPortAOutReg |= (1 << 5);    //USING SHIFT OPERATORS. (To turn ON 5th bit on ODR.)


	while(1){
		*pPortAOutReg |= (1 << 5);
		for (uint32_t i =0 ; i<300000 ; i++);  //random delay
		*pPortAOutReg &= ~(1 << 5); // TO Turn OFF LED.
		for (uint32_t i =0 ; i<300000 ; i++);  //random delay

	}

	while(1);
}
