/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

int main(void)
{
    int i = 0;

    printf("sizeOf = %u\n",sizeof(i));
    printf("SizeOf char data type : %u \n",sizeof(char));
    printf("SizeOf short data type : %u \n",sizeof(short));
    printf("SizeOf int data type : %u \n",sizeof(int));
    printf("SizeOf long data type : %u \n",sizeof(long));
    printf("SizeOf long long data type : %u \n",sizeof(long long));
    printf("SizeOf double data type : %u \n",sizeof(double));

	for(;;);
}
