/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/
void delay (uint32_t count)
{
	for (uint32_t i=0; i< count;i++);
}

int main(void)
{
	// constant peripheral register addresses.
	uint32_t volatile *const pClkCtrlReg = (uint32_t *)(0x40023830);     //clock register starting address.
	uint32_t volatile *const pGpioCModReg = (uint32_t *)(0x40020800);    //GPIO C mode register address starting
	uint32_t volatile *const pOutputDataReg = (uint32_t *)(0x40020800+0x14);  //GPIO C mode register PC0,PC1,PC2,PC3 as Outputs mode
	//with 0x14 offset for output data register.
	uint32_t volatile *const pInputDataReg = (uint32_t *)(0x40020800+0x10);   //GPIO C mode register PC12,PC13,PC14,PC15 as Inputs mode
	//with 0x10 offset for input data register.
	uint32_t volatile *const pPullUpDownReg = (uint32_t *)(0x40020800+0x0C);  //pull Up Pull down register for GPIO C
	//with 0x0C offset for pull Up pull Down register.

	//1. enable clock for the GPIOC peripheral.
	*pClkCtrlReg |= (1 << 2) ; //for GPIO C selection on register. (RCC_AHB1RSTR).

	//2. configure PC0,PC1,PC2,PC3 as output (rows)
	*pGpioCModReg &= ~(0xFF);  //clear the bits
	*pGpioCModReg |= (0x55);   //set bits to set this 4 pins as output.

	//3. configure PC12, PC13, PC14, PC15 as input (column)
	*pGpioCModReg &= ~(0xFF << 24);  //clear the bits and make them as input.

    //4. Enable internal pull up register for PC12,PC13,PC14,PC15.
	*pPullUpDownReg &= ~(0xFF << 24);  //to clear these pins.
	*pPullUpDownReg |= (0x55 << 24) ;  //to set bits as pull up registers. for input.

  while(1){
	//make all rows HIGH
	*pOutputDataReg |= 0x0F;

	//make R1 LOW(PC0)
	*pOutputDataReg &= ~(1 << 0);

	//scan the columns
	//check the PC12 C1 low or high
	if(!(*pInputDataReg & (1 << 12))){
			delay(300000);
			printf("1 \n");
	}
	if(!(*pInputDataReg & (1 << 13))){
		    delay(300000);
			printf("2 \n");
	}
	if(!(*pInputDataReg & (1 << 14))){
		    delay(300000);
			printf("3 \n");
	}
	if(!(*pInputDataReg & (1 << 15))){
			delay(300000);
		 	printf("A \n");
	}

	//make all rows HIGH
		*pOutputDataReg |= 0x0F;
	//make R2 LOW(PC1)
		*pOutputDataReg &= ~(1 << 1);

		//scan the columns
		//check the PC12 C1 low or high
		if(!(*pInputDataReg & (1 << 12))){
				delay(300000);
				printf("4 \n");
		}
		if(!(*pInputDataReg & (1 << 13))){
			    delay(300000);
				printf("5 \n");
		}
		if(!(*pInputDataReg & (1 << 14))){
			    delay(300000);
				printf("6 \n");
		}
		if(!(*pInputDataReg & (1 << 15))){
				delay(300000);
			 	printf("B \n");
		}

		//make all rows HIGH
			*pOutputDataReg |= 0x0F;
		//make R3 LOW(PC2)
			*pOutputDataReg &= ~(1 << 2);

			//scan the columns
			//check the PC12 C1 low or high
			if(!(*pInputDataReg & (1 << 12))){
					delay(300000);
					printf("7 \n");
			}
			if(!(*pInputDataReg & (1 << 13))){
				    delay(300000);
					printf("8 \n");
			}
			if(!(*pInputDataReg & (1 << 14))){
				    delay(300000);
					printf("9 \n");
			}
			if(!(*pInputDataReg & (1 << 15))){
					delay(300000);
				 	printf("C \n");
			}

			//make all rows HIGH
				*pOutputDataReg |= 0x0F;
			//make R4 LOW(PC3)
				*pOutputDataReg &= ~(1 << 3);

				//scan the columns
				//check the PC12 C1 low or high
				if(!(*pInputDataReg & (1 << 12))){
						delay(300000);
						printf("* \n");
				}
				if(!(*pInputDataReg & (1 << 13))){
					    delay(300000);
						printf("0 \n");
				}
				if(!(*pInputDataReg & (1 << 14))){
					    delay(300000);
						printf("# \n");
				}
				if(!(*pInputDataReg & (1 << 15))){
						delay(300000);
					 	printf("D \n");
				}
  } //while end
	while(1);
}
