/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * WAP to enable configurable fault exception, implementing the fault exception handlers and causing the fault by following method:
 * 1. execute undefined instruction.
 * 2. divide by zero floating point error.
 * 3. executing instruction from peripheral region.
 * 4. Executing SVC inside SVC handler
 * 5. Executing SVC instruction inside interrupt handler whose priority is same or lesser than SVC handler.
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 * steps for implementing the fault handler:
 * 1. enable all the configurable exception : 1. usage fault, 2. bus fault, 3. mem manage fault
 * 2. implement the fault handlers
 * 3. now force the processor and implement the causes.
 * 4. analyze the fault.
 */

void undefined_inst(void)
{
	 	 uint32_t *pSinst = (uint32_t*)0x20010000;
	    *pSinst = 0xFFFFFFFF; // invalid opcode.
	    void (*somefunction) (void);   // function pointer.

	    somefunction  = (void *)0x20010000;        // this will cause T-bit invalid state.

	    somefunction();  // calling the function pointer, which will refer to the address of pSinst.

	    // and here it will cause undefined instruction behavior. and it will trigger usage fault.
}

uint32_t func_div(uint32_t x, uint32_t y)
{
	return (x/y);
}

int main(void)
{

	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;   // system handler control and status register.

    *pSHCSR  |= (1 << 18);                      // usage fault enable
    *pSHCSR  |= (1 << 17);                      // Bus fault enable
    *pSHCSR  |= (1 << 16);                      // Memory manage fault enable


    // lets generate undefined instruction.
    //  undefined_inst();

    // lets generate divide by zero.

    func_div(10,0);

	for(;;);
}

void HardFault_Handler (void)
{
	printf("in HardFault Handler \n");
	while(1);
}

void UsageFault_Handler (void)
{
	uint32_t *pUFSR = (uint32_t*)0xE000ED2A; // Usage Fault status register address
	printf("in UsageFault Handler \n");
	printf("pUFSR = %lx \n",(*pUFSR & 0xFFFF));  //checking the value on this register.
	while(1);
}

void BusFault_Handler (void)
{
	printf("in BusFault Handler \n");
	while(1);
}

void MemManage_Handler (void)
{
	printf("in MemManage Handler \n");
	while(1);
}


