/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*Objective of this excercise:
 * Calculation of bit band alias address:
 * Calculate the bit band alias address for the given bit band memory address and bit position.
 * 7th bit position of the memory location 0x20000200 using its alias address
 *
 * General Formula:
 * Alias address = alias_base + (32 *(bit_band_memory_addr - bit_band_base))+ bit * 4
 *
 * here we are using the SRAM address which has only 1MB of bit band memory address region
 * and it has 32MB of bit band alias addresses. which is starting from 0x2200000
 *
 * */

#include <stdint.h>

#define ALIAS_BASE 0x22000000U
#define BIT_BAND_BASE 0x20000000U

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	uint8_t *ptr = (uint8_t *)0x20000200;

	*ptr = 0xFF;

	//normal method to clear 7th bit position.
	//clearing the 7th bit position.
	*ptr &= ~(1 << 7);

	//reset again
	*ptr = 0xFF;
	//using bit-banding method.

	uint8_t *alias_addr = (uint8_t *)(ALIAS_BASE+(32 * (0x20000200 - BIT_BAND_BASE))+ 7 *4);

	//clearing the 7th bit
	*alias_addr = 0;


	for(;;);
}
