/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include <stdint.h>

/*Defining macros for the SRAM stacking assessment for private stack for each task */

#define SIZE_TASK_STACK      			1024U                    // 1KB
#define SIZE_SCHEDULAR_STACK 			1024U                    // 1KB

#define SRAM_START              		0x20000000U                       // starting address of the RAM
#define SRAM_SIZE              			( (128) * (1024) )                // Total size of SRAM of ARM Cortex M4 processor
#define SRAM_END						( (SRAM_START)+(SRAM_SIZE) )      // End address of the SRAM

#define TASK1_PRIVATE_STACK_START    		SRAM_END                                // Task1 private stack assigned
#define TASK2_PRIVATE_STACK_START     		( (SRAM_END) - (1 * SIZE_TASK_STACK) )  // Task2 private stack assigned
#define TASK3_PRIVATE_STACK_START     		( (SRAM_END) - (2 * SIZE_TASK_STACK) )  // Task3 private stack assigned
#define TASK4_PRIVATE_STACK_START     		( (SRAM_END) - (3 * SIZE_TASK_STACK) )  // Task4 private stack assigned
#define SCHEDULAR_PRIVATE_STACK_START     	( (SRAM_END) - (4 * SIZE_TASK_STACK) )  // Schedular private stack assigned

void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

int main(void)
{
    /* Loop forever */
	for(;;);
}

void task1_handler(void)
{
	while(1){
		printf(" In Task 1 handler \n");
	}
}

void task2_handler(void)
{
	while(1){
		printf(" In Task 2 handler \n");
	}
}

void task3_handler(void)
{
	while(1){
		printf(" In Task 3 handler \n");
	}
}

void task4_handler(void)
{
	while(1){
		printf(" In Task 4 handler \n");
	}
}
