/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
/*
 * #if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/
int main(void)
{
	RCC_AHB1ENR_t volatile *const pClkCtrlReg = (RCC_AHB1ENR_t *) 0x40023830; // initialize the clock register pointer variable
	GPIOx_MODE_t volatile *const pGpioAMode = (GPIOx_MODE_t *) 0x40020000;//initialize the mode register pointer variable
	GPIOx_ODR_t volatile *const pPortAOutReg = (GPIOx_ODR_t *) 0x40020014;//initialize the Port A Output register.




	pClkCtrlReg -> gpioA_en = 1;  // make it 1 so that we have enable the PortA for the GPIO.



	//pGpioAMode -> Mode_Pin_10 = 0 ; //clear these bits;

	pGpioAMode -> Mode_Pin_5 = 1 ; // Set it to Output mode.


	pPortAOutReg -> ODR_Pin_5 = 1; //set this pin to high so that LED can be toggled.

    /* Loop forever */
	while(1){
			pPortAOutReg -> ODR_Pin_5 = 1 ; //Turn ON LED
			for (uint32_t i =0 ; i<300000 ; i++);  //random delay
			pPortAOutReg -> ODR_Pin_5 = 0; // TO Turn OFF LED.
			for (uint32_t i =0 ; i<300000 ; i++);  //random delay

		}
	while(1);
}
